spring:
  datasource:
    url: jdbc:h2:mem:espdb
    username: root
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: tre

  h2:
    console:
      enabled: true
      path: /h2
